#include "shell.h"
#include "common.h"

#include <stdio.h>
#include <string.h>

Shell_Type shell_parse_type(const char *name)
{
    if (!name) return SHELL_UNKNOWN;
    if (strcasecmp(name, "bash") == 0) return SHELL_BASH;
    if (strcasecmp(name, "zsh") == 0) return SHELL_ZSH;
    if (strcasecmp(name, "fish") == 0) return SHELL_FISH;
    return SHELL_UNKNOWN;
}

// The hooks record the working directory only when it actually changed.
// Firing `jrun add` from every prompt spawns a process and opens the database
// on each keystroke-to-prompt cycle, which is pure overhead when the user has
// not moved.
static const char *BASH_HOOK =
"# jrun shell integration for bash\n"
"__jrun_last_pwd=\"$PWD\"\n"
"__jrun_completing_from=\n"
"__jrun_track() {\n"
"    local __jrun_status=$?\n"
"    if [ -n \"$__jrun_completing_from\" ]; then\n"
"        builtin cd -- \"$__jrun_completing_from\" 2>/dev/null\n"
"        __jrun_completing_from=\n"
"    fi\n"
"    if [ \"$PWD\" != \"$__jrun_last_pwd\" ]; then\n"
"        __jrun_last_pwd=\"$PWD\"\n"
"        command jrun add \"$PWD\" >/dev/null 2>&1\n"
"    fi\n"
"    return $__jrun_status\n"
"}\n"
"\n"
"# bash 5.1+ allows PROMPT_COMMAND to be an array; append to it properly so we\n"
"# neither clobber another tool's hook nor corrupt the array form.\n"
"if [ -n \"${BASH_VERSION:-}\" ]; then\n"
"    if [[ \"$(declare -p PROMPT_COMMAND 2>/dev/null)\" == \"declare -a\"* ]]; then\n"
"        for __jrun_i in \"${PROMPT_COMMAND[@]}\"; do\n"
"            [ \"$__jrun_i\" = \"__jrun_track\" ] && __jrun_found=1\n"
"        done\n"
"        [ -z \"${__jrun_found:-}\" ] && PROMPT_COMMAND+=(__jrun_track)\n"
"        unset __jrun_i __jrun_found\n"
"    else\n"
"        case \"${PROMPT_COMMAND:-}\" in\n"
"            *__jrun_track*) ;;\n"
"            \"\") PROMPT_COMMAND=\"__jrun_track\" ;;\n"
"            *)  PROMPT_COMMAND=\"__jrun_track;${PROMPT_COMMAND}\" ;;\n"
"        esac\n"
"    fi\n"
"fi\n";

static const char *ZSH_HOOK =
"# jrun shell integration for zsh\n"
"__jrun_track() {\n"
"    command jrun add \"$PWD\" >/dev/null 2>&1\n"
"}\n"
"\n"
"autoload -Uz add-zsh-hook 2>/dev/null\n"
"if typeset -f add-zsh-hook >/dev/null; then\n"
"    add-zsh-hook chpwd __jrun_track\n"
"else\n"
"    chpwd_functions+=(\"__jrun_track\")\n"
"fi\n";

// A program cannot change its parent shell's directory, so jumping has to
// happen in a shell function. Both `j` and `jrun` are defined, so that
// `jrun <target>` jumps in an interactive shell as it always has; the binary's
// print-the-path behaviour is still there as `command jrun <target>`.
static const char *COMMON_POSIX_WRAPPER =
"\n"
"# j <target>           cd to the best match\n"
"# j <target> <cmd>...  run a command there (delegates to the jrun binary)\n"
"# j -                  cd to the previous directory\n"
"# j                    cd to $HOME\n"
"j() {\n"
"    if [ \"$#\" -eq 0 ]; then\n"
"        builtin cd \"$HOME\" || return\n"
"        return 0\n"
"    fi\n"
"\n"
"    if [ \"$#\" -eq 1 ] && [ \"$1\" = \"-\" ]; then\n"
"        builtin cd - || return\n"
"        return 0\n"
"    fi\n"
"\n"
"    # Subcommands and flags go straight through to the binary.\n"
"    case \"$1\" in\n"
"        -h|--help|-v|--version|add|remove|list|query|prune|reindex|doctor|config|root|help|version)\n"
"            command jrun \"$@\"\n"
"            return $?\n"
"            ;;\n"
"    esac\n"
"\n"
"    __jrun_cd() {\n"
"        local __jrun_dir __jrun_rc\n"
"        # The selector renders on /dev/tty, so it still appears even though\n"
"        # stdout is captured here.\n"
"        __jrun_dir=$(command jrun --cd \"$@\") || return $?\n"
"        [ -n \"$__jrun_dir\" ] || return 1\n"
"        builtin cd \"$__jrun_dir\" || return $?\n"
"        __jrun_last_pwd=\"$PWD\"\n"
"        command jrun add \"$PWD\" >/dev/null 2>&1\n"
"        return 0\n"
"    }\n"
"\n"
"    if [ \"$1\" = \"cd\" ] || [ \"$1\" = \"--cd\" ]; then\n"
"        shift\n"
"        __jrun_cd \"$@\"\n"
"        return $?\n"
"    fi\n"
"\n"
"    if [ \"$1\" = \"-i\" ] || [ \"$1\" = \"--interactive\" ]; then\n"
"        shift\n"
"        if [ \"$#\" -eq 1 ]; then\n"
"            local __jrun_dir\n"
"            __jrun_dir=$(command jrun -i --cd \"$1\") || return $?\n"
"            [ -n \"$__jrun_dir\" ] || return 1\n"
"            builtin cd \"$__jrun_dir\" || return $?\n"
"            __jrun_last_pwd=\"$PWD\"\n"
"            command jrun add \"$PWD\" >/dev/null 2>&1\n"
"            return 0\n"
"        fi\n"
"        command jrun -i \"$@\"\n"
"        return $?\n"
"    fi\n"
"\n"
"    if [ \"$#\" -eq 2 ] && [ \"$2\" = \"cd\" ]; then\n"
"        __jrun_cd \"$1\"\n"
"        return $?\n"
"    fi\n"
"\n"
"    if [ \"$#\" -eq 1 ]; then\n"
"        __jrun_cd \"$1\"\n"
"        return $?\n"
"    fi\n"
"\n"
"    # Two or more arguments: target plus a command to run there.\n"
"    command jrun \"$@\"\n"
"}\n"
"\n"
"jrun() {\n"
"    j \"$@\"\n"
"}\n";

// Tab completion. Kept apart from the wrapper because bash and zsh drive
// completion through entirely different machinery.
static const char *BASH_COMPLETION_HELPERS =
"\n"
"# Tab completion for jrun and j. The first word completes to directory names\n"
"# jrun knows about. Everything after it is handed to that command's own\n"
"# completion, run from inside the resolved directory, so `jrun api git ch<Tab>`\n"
"# offers api's branches and `jrun ~ nvim .ba<Tab>` offers files in $HOME.\n"
"__jrun_complete_target() {\n"
"    local cur=\"$1\"\n"
"    case \"$cur\" in\n"
"        -*)\n"
"            mapfile -t COMPREPLY < <(compgen -W \"--help --version --debug --quiet --interactive --yes --cd --init\" -- \"$cur\")\n"
"            ;;\n"
"        /*|\\~*|.|..|./*|../*|*/*)\n"
"            compopt -o filenames 2>/dev/null\n"
"            mapfile -t COMPREPLY < <(compgen -d -- \"$cur\")\n"
"            ;;\n"
"        *)\n"
"            local __jrun_name\n"
"            while IFS= read -r __jrun_name; do\n"
"                COMPREPLY+=(\"$(printf '%q' \"$__jrun_name\")\")\n"
"            done < <(command jrun --complete-target \"$cur\" 2>/dev/null)\n"
"            ;;\n"
"    esac\n"
"}\n"
"\n";

static const char *BASH_COMPLETION_COMMAND =
"# Completes the command after the target: resolves the target, then runs the\n"
"# completion for word $1 onwards of the line from inside that directory.\n"
"__jrun_complete_command() {\n"
"    local target=\"$1\" start=\"$2\" cur=\"${COMP_WORDS[COMP_CWORD]}\"\n"
"    local __jrun_dir\n"
"    __jrun_dir=$(command jrun --resolve \"$target\" 2>/dev/null) || return 0\n"
"    [ -d \"$__jrun_dir\" ] || return 0\n"
"\n"
"    # If Ctrl-C lands mid-completion the cd back below never runs;\n"
"    # __jrun_track sees this at the next prompt and puts the shell back.\n"
"    __jrun_completing_from=\"$PWD\"\n"
"    local __jrun_oldpwd=\"$OLDPWD\"\n"
"    builtin cd -- \"$__jrun_dir\" 2>/dev/null || { __jrun_completing_from=; return 0; }\n"
"\n"
"    local __jrun_offset=\n"
"    if declare -F _comp_command_offset >/dev/null; then\n"
"        __jrun_offset=_comp_command_offset\n"
"    elif declare -F _command_offset >/dev/null; then\n"
"        __jrun_offset=_command_offset\n"
"    fi\n"
"\n"
"    if [ -n \"$__jrun_offset\" ]; then\n"
"        \"$__jrun_offset\" \"$start\"\n"
"    elif [ \"$COMP_CWORD\" -eq \"$start\" ]; then\n"
"        mapfile -t COMPREPLY < <(compgen -c -- \"$cur\")\n"
"    else\n"
"        compopt -o filenames 2>/dev/null\n"
"        mapfile -t COMPREPLY < <(compgen -f -- \"$cur\")\n"
"    fi\n"
"\n"
"    # ble.sh hooks the offset function and takes the candidates out of\n"
"    # COMPREPLY itself, while we are still in the right directory, falling back\n"
"    # to files there when there are none. It leaves COMPREPLY empty, so the\n"
"    # fixes below would only mix in files that do not belong.\n"
"    if [ -n \"$__jrun_offset\" ] && [ -n \"${BLE_ATTACHED-}\" ] &&\n"
"       declare -F \"ble/function#advice/after:$__jrun_offset\" >/dev/null; then\n"
"        :\n"
"    else\n"
"        # Anything readline does after we return happens back in the original\n"
"        # directory. Commands without a completion spec of their own (nvim,\n"
"        # say) ask for readline's default file completion, so do that here.\n"
"        local __jrun_opts\n"
"        __jrun_opts=$(compopt 2>/dev/null)\n"
"        if [ \"${#COMPREPLY[@]}\" -eq 0 ] && [ \"$COMP_CWORD\" -gt \"$start\" ] &&\n"
"           [[ \"$__jrun_opts\" == *\"-o default\"* || \"$__jrun_opts\" == *\"-o bashdefault\"* ]]; then\n"
"            compopt +o default +o bashdefault -o filenames 2>/dev/null\n"
"            __jrun_opts=\"-o filenames\"\n"
"            mapfile -t COMPREPLY < <(compgen -f -- \"$cur\")\n"
"        fi\n"
"\n"
"        # Readline also adds the \"/\" after a directory, so settle a lone match.\n"
"        if [ \"${#COMPREPLY[@]}\" -eq 1 ] && [ -d \"${COMPREPLY[0]}\" ] &&\n"
"           [ \"${COMPREPLY[0]%/}\" = \"${COMPREPLY[0]}\" ] &&\n"
"           [[ \"$__jrun_opts\" == *\"-o filenames\"* ]]; then\n"
"            COMPREPLY[0]=\"${COMPREPLY[0]}/\"\n"
"            compopt -o nospace 2>/dev/null\n"
"        fi\n"
"    fi\n"
"\n"
"    builtin cd -- \"$__jrun_completing_from\" 2>/dev/null\n"
"    OLDPWD=\"$__jrun_oldpwd\"\n"
"    __jrun_completing_from=\n"
"    return 0\n"
"}\n"
"\n";

static const char *BASH_COMPLETION_MAIN =
"__jrun_complete() {\n"
"    local cur=\"${COMP_WORDS[COMP_CWORD]}\"\n"
"    COMPREPLY=()\n"
"\n"
"    local i=1\n"
"    while [ \"$i\" -lt \"$COMP_CWORD\" ]; do\n"
"        case \"${COMP_WORDS[i]}\" in\n"
"            -d|--debug|-q|--quiet|-i|--interactive|-y|--yes) i=$((i + 1)) ;;\n"
"            *) break ;;\n"
"        esac\n"
"    done\n"
"\n"
"    if [ \"$COMP_CWORD\" -eq \"$i\" ]; then\n"
"        __jrun_complete_target \"$cur\"\n"
"        return 0\n"
"    fi\n"
"\n"
"    local target=\"${COMP_WORDS[i]}\"\n"
"    local argn=$((COMP_CWORD - i))\n"
"    case \"$target\" in\n"
"        add|remove)\n"
"            if [ \"$argn\" -eq 1 ]; then\n"
"                compopt -o filenames 2>/dev/null\n"
"                mapfile -t COMPREPLY < <(compgen -d -- \"$cur\")\n"
"            fi\n"
"            return 0\n"
"            ;;\n"
"        root)\n"
"            if [ \"$argn\" -eq 1 ]; then\n"
"                mapfile -t COMPREPLY < <(compgen -W \"list add remove\" -- \"$cur\")\n"
"            elif [ \"$argn\" -eq 2 ] && [ \"${COMP_WORDS[i + 1]}\" != \"list\" ]; then\n"
"                compopt -o filenames 2>/dev/null\n"
"                mapfile -t COMPREPLY < <(compgen -d -- \"$cur\")\n"
"            fi\n"
"            return 0\n"
"            ;;\n"
"        config)\n"
"            [ \"$argn\" -eq 1 ] && mapfile -t COMPREPLY < <(compgen -W \"show edit\" -- \"$cur\")\n"
"            return 0\n"
"            ;;\n"
"        --init|shell)\n"
"            [ \"$argn\" -eq 1 ] && mapfile -t COMPREPLY < <(compgen -W \"bash zsh fish\" -- \"$cur\")\n"
"            return 0\n"
"            ;;\n"
"        cd|--cd|query)\n"
"            [ \"$argn\" -eq 1 ] && __jrun_complete_target \"$cur\"\n"
"            return 0\n"
"            ;;\n"
"        list|prune|reindex|doctor|help|version|-h|--help|-v|--version)\n"
"            return 0\n"
"            ;;\n"
"    esac\n"
"\n"
"    local start=$((i + 1))\n"
"    if [ \"${COMP_WORDS[start]}\" = \"--\" ] && [ \"$COMP_CWORD\" -gt \"$start\" ]; then\n"
"        start=$((start + 1))\n"
"    fi\n"
"\n"
"    __jrun_complete_command \"$target\" \"$start\"\n"
"}\n"
"\n"
"complete -F __jrun_complete jrun j\n";

static const char *ZSH_COMPLETION_HELPERS =
"\n"
"# Tab completion for jrun and j. The first word completes to directory names\n"
"# jrun knows about. Everything after it is handed to that command's own\n"
"# completion, run from inside the resolved directory, so `jrun api git ch<Tab>`\n"
"# offers api's branches and `jrun ~ nvim .ba<Tab>` offers files in $HOME.\n"
"# compdef only exists once compinit has run, so eval this after compinit.\n"
"__jrun_complete_target() {\n"
"    case $PREFIX in\n"
"        -*)\n"
"            compadd -- --help --version --debug --quiet --interactive --yes --cd --init\n"
"            return\n"
"            ;;\n"
"        /*|\\~*|.|..|./*|../*|*/*)\n"
"            _path_files -/\n"
"            return\n"
"            ;;\n"
"    esac\n"
"    local -a names\n"
"    names=(${(f)\"$(command jrun --complete-target \"${(Q)PREFIX}${(Q)SUFFIX}\" 2>/dev/null)\"})\n"
"    # -U: the names are already filtered, and fuzzy ones would not survive\n"
"    # zsh's own prefix matching.\n"
"    (( $#names )) && compadd -U -- \"${names[@]}\"\n"
"}\n"
"\n"
"# zsh decides whether a file match is a directory, and so whether to add a\n"
"# \"/\", when the match is inserted, which is after _jrun has cd'd back. compadd\n"
"# -W names the directory those tests run against, so point it at the real one.\n"
"# Variables are prefixed because compadd reads -a/-d/-O arrays by name from\n"
"# its caller's scope, and a local here could shadow one.\n"
"__jrun_compadd() {\n"
"    local -a __jrun_args\n"
"    local __jrun_a __jrun_file=0 __jrun_seen_w=0\n"
"    while (( $# )); do\n"
"        __jrun_a=$1\n"
"        shift\n"
"        case $__jrun_a in\n"
"            -W)\n"
"                __jrun_seen_w=1\n"
"                [[ $1 == /* ]] || 1=\"$__jrun_comp_dir/$1\"\n"
"                __jrun_args+=(-W \"$1\")\n"
"                shift\n"
"                ;;\n"
"            -W?*)\n"
"                __jrun_seen_w=1\n"
"                __jrun_a=${__jrun_a#-W}\n"
"                [[ $__jrun_a == /* ]] || __jrun_a=\"$__jrun_comp_dir/$__jrun_a\"\n"
"                __jrun_args+=(-W \"$__jrun_a\")\n"
"                ;;\n"
"            -|--)\n"
"                __jrun_args+=(\"$__jrun_a\" \"$@\")\n"
"                break\n"
"                ;;\n"
"            -[!-]*f*)\n"
"                __jrun_file=1\n"
"                __jrun_args+=(\"$__jrun_a\")\n"
"                ;;\n"
"            *)\n"
"                __jrun_args+=(\"$__jrun_a\")\n"
"                ;;\n"
"        esac\n"
"    done\n"
"    if (( __jrun_file && ! __jrun_seen_w )); then\n"
"        __jrun_args=(-W \"$__jrun_comp_dir/\" \"${__jrun_args[@]}\")\n"
"    fi\n"
"    if (( $+functions[__jrun_prev_compadd] )); then\n"
"        __jrun_prev_compadd \"${__jrun_args[@]}\"\n"
"    else\n"
"        builtin compadd \"${__jrun_args[@]}\"\n"
"    fi\n"
"}\n"
"\n";

static const char *ZSH_COMPLETION_MAIN =
"_jrun() {\n"
"    local -i i=2\n"
"    while (( i < CURRENT )); do\n"
"        case $words[i] in\n"
"            -d|--debug|-q|--quiet|-i|--interactive|-y|--yes) (( i++ )) ;;\n"
"            *) break ;;\n"
"        esac\n"
"    done\n"
"\n"
"    if (( CURRENT == i )); then\n"
"        __jrun_complete_target\n"
"        return\n"
"    fi\n"
"\n"
"    local target=${(Q)words[i]}\n"
"    local -i argn=$(( CURRENT - i ))\n"
"    case $target in\n"
"        add|remove)\n"
"            (( argn == 1 )) && _path_files -/\n"
"            return\n"
"            ;;\n"
"        root)\n"
"            if (( argn == 1 )); then\n"
"                compadd -- list add remove\n"
"            elif (( argn == 2 )) && [[ $words[i+1] != list ]]; then\n"
"                _path_files -/\n"
"            fi\n"
"            return\n"
"            ;;\n"
"        config)\n"
"            (( argn == 1 )) && compadd -- show edit\n"
"            return\n"
"            ;;\n"
"        --init|shell)\n"
"            (( argn == 1 )) && compadd -- bash zsh fish\n"
"            return\n"
"            ;;\n"
"        cd|--cd|query)\n"
"            (( argn == 1 )) && __jrun_complete_target\n"
"            return\n"
"            ;;\n"
"        list|prune|reindex|doctor|help|version|-h|--help|-v|--version)\n"
"            return\n"
"            ;;\n"
"    esac\n"
"\n"
"    local -i start=$(( i + 1 ))\n"
"    if [[ $words[start] == -- ]] && (( CURRENT > start )); then\n"
"        start=$(( start + 1 ))\n"
"    fi\n"
"\n"
"    local dir\n"
"    dir=$(command jrun --resolve \"$target\" 2>/dev/null) || return\n"
"    [[ -d $dir ]] || return\n"
"\n"
"    # -q keeps chpwd hooks, including jrun's own tracking, out of it, but\n"
"    # OLDPWD still moves, so `cd -` needs putting back too.\n"
"    local oldpwd=$PWD oldoldpwd=$OLDPWD __jrun_comp_dir=$dir\n"
"    local prev_compadd=${functions[compadd]-}\n"
"    {\n"
"        builtin cd -q -- \"$dir\" 2>/dev/null || return\n"
"        # Chain to any compadd override already in place (fzf-tab has one).\n"
"        [[ -n $prev_compadd ]] && functions[__jrun_prev_compadd]=$prev_compadd\n"
"        functions[compadd]='__jrun_compadd \"$@\"'\n"
"        words=(\"${(@)words[start,-1]}\")\n"
"        CURRENT=$(( CURRENT - start + 1 ))\n"
"        _normal\n"
"    } always {\n"
"        if [[ -n $prev_compadd ]]; then\n"
"            functions[compadd]=$prev_compadd\n"
"            unfunction __jrun_prev_compadd 2>/dev/null\n"
"        else\n"
"            unfunction compadd 2>/dev/null\n"
"        fi\n"
"        builtin cd -q -- \"$oldpwd\" 2>/dev/null\n"
"        OLDPWD=$oldoldpwd\n"
"    }\n"
"}\n"
"\n"
"if (( $+functions[compdef] )); then\n"
"    compdef _jrun jrun j\n"
"fi\n";

static const char *FISH_INIT =
"# jrun shell integration for fish\n"
"function __jrun_track --on-variable PWD\n"
"    status is-command-substitution; and return\n"
"    set -q __jrun_completing; and return\n"
"    test -d \"$PWD\"; and command jrun add \"$PWD\" >/dev/null 2>&1\n"
"end\n"
"\n"
"function __jrun_cd\n"
"    set -l dir (command jrun --cd $argv)\n"
"    set -l rc $status\n"
"    test $rc -eq 0; or return $rc\n"
"    test -n \"$dir\"; or return 1\n"
"    builtin cd \"$dir\"; or return $status\n"
"    return 0\n"
"end\n"
"\n"
"# --wraps gives j the jrun completions. A plain `complete -c j` is not enough:\n"
"# fish ships a j.fish for autojump that erases it the first time j is completed.\n"
"function j --wraps jrun --description 'jump to a project directory'\n"
"    set -l argc (count $argv)\n"
"    if test $argc -eq 0\n"
"        builtin cd $HOME\n"
"        return 0\n"
"    end\n"
"\n"
"    if test $argc -eq 1 -a \"$argv[1]\" = \"-\"\n"
"        builtin cd -\n"
"        return 0\n"
"    end\n"
"\n"
"    switch \"$argv[1]\"\n"
"        case -h --help -v --version add remove list query prune reindex doctor config root help version\n"
"            command jrun $argv\n"
"            return $status\n"
"    end\n"
"\n"
"    if test \"$argv[1]\" = \"cd\" -o \"$argv[1]\" = \"--cd\"\n"
"        set -e argv[1]\n"
"        __jrun_cd $argv\n"
"        return $status\n"
"    end\n"
"\n"
"    if test \"$argv[1]\" = \"-i\" -o \"$argv[1]\" = \"--interactive\"\n"
"        set -e argv[1]\n"
"        if test (count $argv) -eq 1\n"
"            set -l dir (command jrun -i --cd \"$argv[1]\")\n"
"            test $status -eq 0 -a -n \"$dir\"; and builtin cd \"$dir\"\n"
"            return $status\n"
"        end\n"
"        command jrun -i $argv\n"
"        return $status\n"
"    end\n"
"\n"
"    if test $argc -eq 2 -a \"$argv[2]\" = \"cd\"\n"
"        __jrun_cd \"$argv[1]\"\n"
"        return $status\n"
"    end\n"
"\n"
"    if test $argc -eq 1\n"
"        __jrun_cd \"$argv[1]\"\n"
"        return $status\n"
"    end\n"
"\n"
"    command jrun $argv\n"
"end\n"
"\n"
"function jrun --description 'jump to or run a command in a project directory'\n"
"    j $argv\n"
"end\n";

static const char *FISH_COMPLETION =
"\n"
"# Tab completion for jrun and j. The first word completes to directory names\n"
"# jrun knows about. Everything after it is completed as its own command line\n"
"# from inside the resolved directory, so `jrun api git ch<Tab>` offers api's\n"
"# branches and `jrun ~ nvim .ba<Tab>` offers files in $HOME.\n"
"function __jrun_complete_target\n"
"    switch \"$argv[1]\"\n"
"        case '-*'\n"
"            printf '%s\\n' --help --version --debug --quiet --interactive --yes --cd --init\n"
"        case '/*' '~*' . .. './*' '../*' '*/*'\n"
"            __fish_complete_directories \"$argv[1]\"\n"
"        case '*'\n"
"            command jrun --complete-target \"$argv[1]\" 2>/dev/null\n"
"    end\n"
"end\n"
"\n"
"function __jrun_complete\n"
"    set -l tokens (commandline -opc)\n"
"    set -l cur (commandline -ct)\n"
"    set -e tokens[1]\n"
"    while set -q tokens[1]; and contains -- $tokens[1] -d --debug -q --quiet -i --interactive -y --yes\n"
"        set -e tokens[1]\n"
"    end\n"
"\n"
"    if not set -q tokens[1]\n"
"        __jrun_complete_target \"$cur\"\n"
"        return\n"
"    end\n"
"\n"
"    set -l target $tokens[1]\n"
"    set -e tokens[1]\n"
"    set -l argn (math (count $tokens) + 1)\n"
"    switch $target\n"
"        case add remove\n"
"            test $argn -eq 1; and __fish_complete_directories \"$cur\"\n"
"            return\n"
"        case root\n"
"            if test $argn -eq 1\n"
"                printf '%s\\n' list add remove\n"
"            else if test $argn -eq 2 -a \"$tokens[1]\" != list\n"
"                __fish_complete_directories \"$cur\"\n"
"            end\n"
"            return\n"
"        case config\n"
"            test $argn -eq 1; and printf '%s\\n' show edit\n"
"            return\n"
"        case --init shell\n"
"            test $argn -eq 1; and printf '%s\\n' bash zsh fish\n"
"            return\n"
"        case cd --cd query\n"
"            test $argn -eq 1; and __jrun_complete_target \"$cur\"\n"
"            return\n"
"        case list prune reindex doctor help version -h --help -v --version\n"
"            return\n"
"    end\n"
"\n"
"    if test \"$tokens[1]\" = --\n"
"        set -e tokens[1]\n"
"    end\n"
"\n"
"    set -l dir (command jrun --resolve $target 2>/dev/null)\n"
"    or return\n"
"    test -d \"$dir\"; or return\n"
"\n"
"    # __jrun_completing keeps the PWD hook from recording this visit.\n"
"    set -l oldpwd $PWD\n"
"    set -g __jrun_completing 1\n"
"    if builtin cd $dir 2>/dev/null\n"
"        complete -C (string join ' ' -- (string escape -- $tokens) \"$cur\")\n"
"        builtin cd $oldpwd\n"
"    end\n"
"    set -e __jrun_completing\n"
"end\n"
"\n"
"complete -c jrun -f -k -a '(__jrun_complete)'\n";


bool shell_generate_init(Shell_Type shell)
{
    switch (shell) {
    case SHELL_BASH:
        printf("%s%s%s%s%s", BASH_HOOK, COMMON_POSIX_WRAPPER, BASH_COMPLETION_HELPERS,
               BASH_COMPLETION_COMMAND, BASH_COMPLETION_MAIN);
        return true;
    case SHELL_ZSH:
        printf("%s%s%s%s", ZSH_HOOK, COMMON_POSIX_WRAPPER, ZSH_COMPLETION_HELPERS,
               ZSH_COMPLETION_MAIN);
        return true;
    case SHELL_FISH:
        printf("%s%s", FISH_INIT, FISH_COMPLETION);
        return true;
    case SHELL_UNKNOWN:
    default:
        jrun_log_error("unsupported shell. Supported shells: bash, zsh, fish");
        return false;
    }
}
